use crate::utils::get_cache_dir;
use reqwest::Client;
use scraper::{Html, Selector};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::fs::File;
use std::fs::{create_dir_all, remove_dir_all, remove_file, OpenOptions};
use std::io::Read;
use std::io::Write;
use tauri::Manager;

#[derive(Serialize, Deserialize)]
struct GameInfo {
    appid: String,
    name: String,
}

#[derive(Serialize, Deserialize)]
struct GameData {
    appid: u64,
    name: String,
    playtime_forever: u64,
}

//Modified to read from games_list.json at working directory, generated by SteamGameFetcher
#[tauri::command]
pub async fn get_games_list(
    steam_id: String,
    app_handle: tauri::AppHandle,
) -> Result<Value, String> {
    // Run SteamGameFetcher.exe --json and wait for games_list.json to update
    run_steam_game_fetcher().await?;

    let games_list = read_games_list_from_exe_dir()?;

    if games_list.is_empty() {
        return Ok(json!({ "games_list": [] }));
    }

    let app_data_dir = get_cache_dir(&app_handle)?.join(steam_id.clone());
    create_dir_all(&app_data_dir)
        .map_err(|e| format!("Failed to create app directory: {}", e))?;

    // Save the response to games_list.json
    let file_name = format!("games_list.json");
    let games_file_path = app_data_dir.join(file_name);
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(&games_file_path)
        .map_err(|e| format!("Failed to open games list file: {}", e))?;

    let json_string = serde_json::to_string_pretty(&json!({ "games_list": games_list }))
        .map_err(|e| format!("Failed to serialize games list: {}", e))?;
    file.write_all(json_string.as_bytes())
        .map_err(|e| format!("Failed to write games list to file: {}", e))?;

    Ok(json!({ "games_list": games_list }))
}

#[tauri::command]
pub async fn get_recent_games(
    steam_id: String,
    api_key: Option<String>,
    app_handle: tauri::AppHandle,
) -> Result<Value, String> {
    // Get the API key from the envor use the provided one
    let key = api_key.unwrap_or_else(|| std::env::var("KEY").unwrap());
    let url = format!(
        "https://api.steampowered.com/IPlayerService/GetRecentlyPlayedGames/v1/?key={}&steamid={}",
        key, steam_id
    );

    let client = Client::new();

    // Send the request and handle the response
    match client.get(&url).send().await {
        Ok(response) => {
            let body: Value = response.json().await.map_err(|e| e.to_string())?;

            // Process the response to extract only needed fields
            let filtered_data = filter_game_data(&body)?;

            let game_data = json!({
                "games_list": filtered_data
            });

            let app_data_dir = get_cache_dir(&app_handle)?.join(steam_id.clone());
            create_dir_all(&app_data_dir)
                .map_err(|e| format!("Failed to create app directory: {}", e))?;

            // Save the filtered response to recent_games.json
            let file_name = format!("recent_games.json");
            let recent_games_file_path = app_data_dir.join(file_name);
            let mut file = OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .open(&recent_games_file_path)
                .map_err(|e| format!("Failed to open recent games file: {}", e))?;

            let json_string = serde_json::to_string_pretty(&game_data)
                .map_err(|e| format!("Failed to serialize recent games: {}", e))?;
            file.write_all(json_string.as_bytes())
                .map_err(|e| format!("Failed to write recent games to file: {}", e))?;

            Ok(game_data)
        }
        Err(err) => Err(err.to_string()),
    }
}

// Helper: Reads games_list.json from the exe directory
fn read_games_list_from_exe_dir() -> Result<Vec<GameData>, String> {
    let mut path = std::env::current_exe().map_err(|e| e.to_string())?;
    path.pop();
    path.push("games_list.json");

    if !path.exists() {
        return Ok(vec![]);
    }

    let mut file = File::open(&path)
        .map_err(|e| format!("Failed to open games_list.json: {}", e))?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)
        .map_err(|e| format!("Failed to read games_list.json: {}", e))?;

    let contents = contents.strip_prefix('\u{feff}').unwrap_or(&contents);

    let parsed: Value = serde_json::from_str(contents)
        .map_err(|e| format!("Failed to parse games_list.json: {}", e))?;

    let games = match &parsed["games_list"] {
        Value::Array(arr) => arr,
        _ => return Ok(vec![]),
    };

    let result: Vec<GameData> = games
        .iter()
        .filter_map(|game| {
            let appid = game["appid"].as_u64()?;
            let name = game["name"].as_str()?.to_string();
            let playtime_forever = game["playtime_forever"].as_u64().unwrap_or(0);
            Some(GameData { appid, name, playtime_forever })
        })
        .collect();

    Ok(result)
}

// Helper: Runs SteamGameFetcher.exe and waits for games_list.json to update
async fn run_steam_game_fetcher() -> Result<(), String> {
    use std::process::Command;
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::time::{Duration, Instant};

    static IS_FETCHER_RUNNING: AtomicBool = AtomicBool::new(false);

    let mut exe_dir = std::env::current_exe().map_err(|e| e.to_string())?;
    exe_dir.pop();
    let fetcher_path = exe_dir.join("SteamGameFetcher.exe");
    let json_path = exe_dir.join("games_list.json");

    let initial_modified = std::fs::metadata(&json_path)
        .ok()
        .and_then(|m| m.modified().ok());

    let should_spawn = IS_FETCHER_RUNNING
        .compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst)
        .is_ok();

    if should_spawn {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x08000000;
        Command::new(&fetcher_path)
            .arg("--json")
            .current_dir(&exe_dir)
            .creation_flags(CREATE_NO_WINDOW)
            .spawn()
            .map_err(|e| {
                IS_FETCHER_RUNNING.store(false, Ordering::SeqCst);
                format!("Failed to run SteamGameFetcher.exe: {}", e)
            })?;
    }

    let timeout = Duration::from_secs(120);
    let poll_interval = Duration::from_millis(250);
    let start = Instant::now();

    loop {
        if start.elapsed() > timeout {
            if should_spawn {
                IS_FETCHER_RUNNING.store(false, Ordering::SeqCst);
            }
            return Err("Timed out waiting for games_list.json to update".into());
        }

        tokio::time::sleep(poll_interval).await;

        let current_modified = std::fs::metadata(&json_path)
            .ok()
            .and_then(|m| m.modified().ok());

        match (&initial_modified, &current_modified) {
            (Some(initial), Some(current)) if current > initial => break,
            (None, Some(_)) => break,
            _ => continue,
        }
    }

    if should_spawn {
        IS_FETCHER_RUNNING.store(false, Ordering::SeqCst);
    }

    Ok(())
}


// Helper function to filter game data from Steam API response
fn filter_game_data(data: &Value) -> Result<Value, String> {
    let games = match &data["response"]["games"] {
        Value::Array(games) => games,
        _ => return Ok(json!([])),
    };

    let filtered_games: Vec<GameData> = games
        .iter()
        .filter_map(|game| {
            let appid = game["appid"].as_u64()?;
            let name = game["name"].as_str()?.to_string();
            let playtime_forever = game["playtime_forever"].as_u64().unwrap_or(0);

            Some(GameData {
                appid,
                name,
                playtime_forever,
            })
        })
        .collect();

    Ok(json!(filtered_games))
}

#[tauri::command]
pub fn get_games_list_cache(
    steam_id: String,
    app_handle: tauri::AppHandle,
) -> Result<Value, String> {
    let app_data_dir = get_cache_dir(&app_handle)?.join(steam_id.clone());

    // Read games list file from cache
    let games_list = {
        let file_name = format!("games_list.json");
        let games_file_path = app_data_dir.join(file_name);
        if games_file_path.exists() {
            let mut file = File::open(&games_file_path)
                .map_err(|e| format!("Failed to open games list file: {}", e))?;
            let mut contents = String::new();
            file.read_to_string(&mut contents)
                .map_err(|e| format!("Failed to read games list file: {}", e))?;
            let parsed: Value = serde_json::from_str(&contents)
                .map_err(|e| format!("Failed to parse games list JSON: {}", e))?;

            // Extract the games_list array from the parsed object
            parsed.get("games_list").cloned().unwrap_or(json!({}))
        } else {
            match read_games_list_from_exe_dir() {
                Ok(games) => json!(games),
                Err(_) => json!([]),
            }
        }
    };

    // Read recent games file
    let recent_games = {
        let file_name = format!("recent_games.json");
        let recent_games_file_path = app_data_dir.join(file_name);
        if recent_games_file_path.exists() {
            let mut file = File::open(&recent_games_file_path)
                .map_err(|e| format!("Failed to open recent games file: {}", e))?;
            let mut contents = String::new();
            file.read_to_string(&mut contents)
                .map_err(|e| format!("Failed to read recent games file: {}", e))?;
            let parsed: Value = serde_json::from_str(&contents)
                .map_err(|e| format!("Failed to parse recent games JSON: {}", e))?;

            // Extract the games_list array from the parsed object
            parsed.get("games_list").cloned().unwrap_or(json!({}))
        } else {
            json!({})
        }
    };

    Ok(json!({
        "games_list": games_list,
        "recent_games": recent_games
    }))
}

#[tauri::command]
pub fn delete_user_games_list_files(
    steam_id: String,
    app_handle: tauri::AppHandle,
) -> Result<(), String> {
    let games_list_file_name = format!("games_list.json");
    let recent_games_file_name = format!("recent_games.json");
    let app_data_dir = get_cache_dir(&app_handle)?.join(steam_id.clone());
    // Delete the games list file
    let games_file_path = app_data_dir.join(games_list_file_name);
    if games_file_path.exists() {
        remove_file(&games_file_path)
            .map_err(|e| format!("Failed to delete games list file: {}", e))?;
    }
    // Delete the recent games file
    let recent_games_file_path = app_data_dir.join(recent_games_file_name);
    if recent_games_file_path.exists() {
        remove_file(&recent_games_file_path)
            .map_err(|e| format!("Failed to delete recent games file: {}", e))?;
    }

    Ok(())
}

#[tauri::command]
pub fn delete_all_cache_files(app_handle: tauri::AppHandle) -> Result<(), String> {
    let cache_data_dir = get_cache_dir(&app_handle)?;
    // Delete the cache directory
    match remove_dir_all(&cache_data_dir) {
        Ok(_) => println!("Successfully deleted directory: {:?}", cache_data_dir),
        Err(e) => println!(
            "Failed to delete directory: {:?}, Error: {}",
            cache_data_dir, e
        ),
    }

    Ok(())
}

#[tauri::command]
pub async fn get_free_games() -> Result<serde_json::Value, String> {
    let client = Client::new();
    let url =
        "https://store.steampowered.com/search/?l=english&maxprice=free&specials=1&category1=998";

    let response = client.get(url).send().await.map_err(|e| e.to_string())?;

    let html = response.text().await.map_err(|e| e.to_string())?;
    let document = Html::parse_document(&html);

    let a_selector = Selector::parse("a.search_result_row").unwrap();
    let title_selector = Selector::parse("span.title").unwrap();

    let mut free_games = Vec::new();

    // Parse the HTML to find free games
    for element in document.select(&a_selector) {
        if let Some(app_id) = element.value().attr("data-ds-appid") {
            if let Some(title_element) = element.select(&title_selector).next() {
                let name = title_element.text().collect::<String>();
                free_games.push(GameInfo {
                    appid: app_id.to_string(),
                    name: name.trim().to_string(),
                });
            }
        }
    }

    Ok(json!({ "games": free_games }))
}

// Redeem a free game by opening the Steam store page and clicking the "Add to Library" button if available
#[tauri::command]
pub async fn redeem_free_game(
    app_handle: tauri::AppHandle,
    app_id: String,
) -> Result<Value, String> {
    use std::time::Duration;

    // Construct the URL for the game page
    let url = format!("https://store.steampowered.com/app/{}", app_id);

    // Create a hidden window for the game page
    let window = tauri::webview::WebviewWindowBuilder::new(
        &app_handle,
        &format!("steam-redeem-{}", app_id),
        tauri::WebviewUrl::External(url.parse().unwrap()),
    )
    .title(&format!("Redeeming Free Game {}", app_id))
    .inner_size(0.0, 0.0)
    .visible(false)
    .build()
    .map_err(|e| e.to_string())?;

    // Wait a moment for the page to load
    tokio::time::sleep(Duration::from_millis(5000)).await;

    // Poll for the "Add to Account" button up to 5 times, every second
    for _ in 0..5 {
        if let Some(webview) = window.get_webview(&format!("steam-redeem-{}", app_id)) {
            // Execute JavaScript to check for the button and click it
            let js_check = r#"
                (function() {
                    console.log('=== Debug: Starting button search ===');
                    
                    // Check for btn_addtocart div
                    const cartDiv = document.querySelector('.btn_addtocart');
                    console.log('btn_addtocart div found:', !!cartDiv);
                    if (cartDiv) {
                        console.log('btn_addtocart HTML:', cartDiv.innerHTML);
                    }
                    
                    // Try different selectors
                    const btn1 = document.querySelector('.btn_addtocart a');
                    console.log('Selector ".btn_addtocart a" found:', !!btn1);
                    
                    const btn2 = document.querySelector('.btn_addtocart a.btn_green_steamui');
                    console.log('Selector ".btn_addtocart a.btn_green_steamui" found:', !!btn2);
                    
                    const btn3 = document.querySelector('a.btn_green_steamui[href*="addToCart"]');
                    console.log('Selector "a.btn_green_steamui[href*="addToCart"]" found:', !!btn3);
                    
                    const btn4 = document.querySelector('.btn_addtocart a[href*="addToCart"]');
                    console.log('Selector ".btn_addtocart a[href*="addToCart"]" found:', !!btn4);
                    
                    // Use the most specific selector
                    const btn = document.querySelector('.btn_addtocart a[href*="addToCart"]');
                    if (!btn) {
                        console.error('Button not found with any selector');
                        throw new Error('Button not found');
                    }
                    
                    console.log('Found button:', btn);
                    const href = btn.getAttribute('href');
                    console.log('Button href:', href);
                    
                    const match = href.match(/addToCart\(\s*(\d+)\s*\)/);
                    if (!match) {
                        console.error('No match for product ID in href:', href);
                        throw new Error('No match for product ID');
                    }
                    
                    const productId = match[1];
                    console.log('Found product ID:', productId);
                    
                    // Call the addToCart function
                    console.log('Calling addToCart with product ID:', productId);
                    addToCart(productId);
                    
                    return true;
                })();
            "#;

            match webview.eval(js_check) {
                Ok(_) => {
                    // Button found and clicked, wait a bit then close
                    tokio::time::sleep(Duration::from_millis(500)).await;
                    let _ = window.close();
                    return Ok(serde_json::json!({
                        "success": true,
                        "message": "Free game redeemed successfully"
                    }));
                }
                Err(e) => {
                    // JS execution failed (button not found), continue polling
                    println!("JS execution error: {}", e);
                }
            }
        } else {
            // Window or webview no longer exists
            return Ok(serde_json::json!({
                "success": false,
                "message": "Redeem window closed unexpectedly"
            }));
        }

        tokio::time::sleep(Duration::from_secs(1)).await;
    }

    // If we reach here, the button was not found
    let _ = window.close();
    Ok(serde_json::json!({
        "success": false,
        "message": "Could not find redeem button or game is not free"
    }))
}
